#!/usr/bin/env python3
"""Generate coverage/dashboard.html — a read-only, single-file view of the vault.

Pure view: reads dossier frontmatter, valuation logs, pending decisions, and the
sentinel heartbeat. No framework, no server; regenerated by every sentinel pass
and committed to git (phone-readable via GitHub). A JS banner self-reddens when
the page is older than 36h — the cheapest possible dead-man's switch.
"""
import datetime, html, json, os, re

REPO = os.environ.get('BAV_REPO') or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COVERAGE = os.path.join(REPO, 'coverage')


def frontmatter(path):
    try:
        m = re.match(r'^---\n(.*?)\n---', open(path).read(), re.S)
    except OSError:
        return {}
    if not m:
        return {}
    return {k.strip(): v.strip().strip('"') for k, v in
            (line.split(':', 1) for line in m.group(1).splitlines() if ':' in line)}


def clean(v):
    """Frontmatter nulls/empties render as an em-dash, not the string 'null'."""
    return '—' if v in (None, '', 'null', 'None') else v


def val_log(ticker):
    path = os.path.join(COVERAGE, ticker, 'valuation_log.csv')
    if not os.path.exists(path):
        return []
    rows = [l.split(',') for l in open(path).read().strip().splitlines()[1:]]
    return [r for r in rows if len(r) >= 8]


def spark(values, w=120, h=26):
    pts = [v for v in values if v]
    if len(pts) < 2:
        return ''
    lo, hi = min(pts), max(pts)
    rng = (hi - lo) or 1.0
    step = w / (len(pts) - 1)
    coords = ' '.join(f'{i*step:.0f},{h - 2 - (v - lo) / rng * (h - 6):.0f}'
                      for i, v in enumerate(pts))
    return (f'<svg width="{w}" height="{h}"><polyline points="{coords}" '
            f'fill="none" stroke="#4472c4" stroke-width="1.5"/></svg>')


def pending_count(ticker):
    path = os.path.join(COVERAGE, ticker, 'pending_decisions.md')
    if not os.path.exists(path):
        return 0, 0
    ages = [(datetime.date.today() - datetime.date.fromisoformat(m.group(1))).days
            for m in re.finditer(r'\[pending since (\d{4}-\d{2}-\d{2})\]', open(path).read())]
    return len(ages), max(ages, default=0)


def main():
    now = datetime.datetime.now()
    hb_path = os.path.join(COVERAGE, '_state', 'heartbeat')
    hb = 'never'
    if os.path.exists(hb_path):
        try:
            age_h = (now - datetime.datetime.fromisoformat(
                open(hb_path).read().strip())).total_seconds() / 3600
            hb = f'{age_h:.0f}h ago'
        except ValueError:
            hb = 'unreadable'

    rows = []
    for name in sorted(os.listdir(COVERAGE)):
        d = os.path.join(COVERAGE, name)
        if name.startswith('_') or not os.path.isdir(d):
            continue
        fm = frontmatter(os.path.join(d, 'dossier.md'))
        if not fm.get('ticker'):
            continue
        t = fm['ticker']
        log_rows = val_log(t)
        weighted = []
        for r in log_rows:
            try:
                weighted.append(float(r[6]))
            except (ValueError, IndexError):
                weighted.append(None)
        npend, maxage = pending_count(t)
        stale = fm.get('status') != 'current'
        pend_html = (f'<span class="bad">{npend} (max {maxage}d)</span>'
                     if maxage >= 7 else (str(npend) if npend else '—'))
        gap = clean(fm.get('gap_pct'))
        rows.append(f"""<tr{' class="stale"' if stale else ''}>
<td><b>{html.escape(t)}</b><br><small>{html.escape(clean(fm.get('company','')))}</small></td>
<td>{html.escape(clean(fm.get('weighted_ivps')))}</td>
<td>{html.escape(clean(fm.get('price_at_update')))}<br><small>{html.escape(clean(fm.get('price_date','')) if fm.get('price_date') not in (None,'null') else '')}</small></td>
<td>{html.escape(gap)}{'%' if gap != '—' else ''}</td>
<td>{spark(weighted)}</td>
<td>{html.escape(fm.get('last_update','—'))}</td>
<td>{html.escape(fm.get('status','?'))}</td>
<td>{pend_html}</td>
<td><small>{html.escape((fm.get('next_catalyst','') or '')[:60])}</small></td></tr>""")

    doc = f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>BAV Coverage</title><style>
body{{font:14px -apple-system,Segoe UI,sans-serif;margin:24px;color:#1a1a1a}}
table{{border-collapse:collapse;width:100%}}
td,th{{padding:8px 10px;border-bottom:1px solid #e5e5e5;text-align:left;vertical-align:top}}
th{{background:#f4f6fa;font-size:12px;text-transform:uppercase;letter-spacing:.04em}}
tr.stale td{{background:#fff8f0}} .bad{{color:#c0392b;font-weight:600}}
#banner{{padding:10px 14px;border-radius:8px;background:#e8f0e8;margin-bottom:18px;font-size:13px}}
#banner.old{{background:#f8d7da;font-weight:600}}
small{{color:#777}}</style></head><body>
<div id="banner" data-gen="{now.isoformat()}">Generated {now:%Y-%m-%d %H:%M} ·
sentinel heartbeat: {hb} · this page self-flags if older than 36h</div>
<h2>BAV Coverage Universe</h2>
<table><tr><th>Ticker</th><th>Weighted IVPS</th><th>Price (as of)</th><th>Gap</th>
<th>Trajectory</th><th>Last update</th><th>Status</th><th>Pending</th><th>Next catalyst</th></tr>
{''.join(rows)}</table>
<p><small>Read-only view generated by automation/build_dashboard.py — the files in
coverage/ are the source of truth. Pending = entries in pending_decisions.md awaiting
an interactive gate (run /bav-update TICKER).</small></p>
<script>
const g=new Date(document.getElementById('banner').dataset.gen);
if((Date.now()-g)/36e5>36){{const b=document.getElementById('banner');
b.classList.add('old');b.textContent='STALE: generated '+g.toLocaleString()+
' — the sentinel may be dead. Check launchctl + coverage/_state/heartbeat.';}}
</script></body></html>"""
    out = os.path.join(COVERAGE, 'dashboard.html')
    tmp = out + '.tmp'
    open(tmp, 'w').write(doc)
    os.replace(tmp, out)
    print(f'dashboard: {out} ({len(rows)} tickers)')


if __name__ == '__main__':
    main()
